trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - CHANGELOG.md
  tags:
    include:
      - "v*"
    exclude:
      - "*-*"

parameters:
  - name: PlatformMatrix
    type: object
    default:
      Windows_PWSH7:
        vmImage: windows-latest
        usePwsh: true
        platformName: Windows_PWSH7
      Windows_PWSH5:
        vmImage: windows-latest
        usePwsh: false
        platformName: Windows_PWSH5
      Ubuntu_PWSH7:
        vmImage: ubuntu-latest
        usePwsh: true
        platformName: Ubuntu_PWSH7
      MacOS_PWSH7:
        vmImage: macos-latest
        usePwsh: true
        platformName: MacOS_PWSH7

variables:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  defaultBranch: master
  Agent.Source.Git.ShallowFetchDepth: 0

stages:
  - stage: Build
    jobs:
      - job: Package_Module
        displayName: Package Module
        pool:
          vmImage: ubuntu-latest
        steps:
          - pwsh: |
              dotnet tool install --global GitVersion.Tool --version 5.*
              $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
              $gitVersionObject.PSObject.Properties.ForEach{
                  Write-Host -Object "Setting task variable '$($_.Name)' to '$($_.Value)'."
                  Write-Host -Object "##vso[task.setvariable variable=$($_.Name);]$($_.Value)"
              }
              Write-Host -Object "##vso[build.updatebuildnumber]$($gitVersionObject.FullSemVer)"
            displayName: Calculate ModuleVersion

          - task: PowerShell@2
            displayName: Build and Package Module
            inputs:
              filePath: ./build.ps1
              arguments: -ResolveDependency -Tasks pack
              pwsh: true
            env:
              ModuleVersion: $(NuGetVersionV2)

          - task: PublishPipelineArtifact@1
            displayName: Publish Build Artifact
            inputs:
              targetPath: $(buildFolderName)
              artifact: $(buildArtifactName)
              publishLocation: pipeline
              parallel: true

  - stage: Test
    dependsOn: Build
    jobs:
      - job: Test
        strategy:
          matrix:
            ${{ parameters.PlatformMatrix }}
        timeoutInMinutes: 0
        pool:
          vmImage: $[ variables['vmImage'] ]
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              buildType: current
              artifactName: $(buildArtifactName)
              targetPath: $(Build.SourcesDirectory)/$(buildFolderName)

          - task: PowerShell@2
            displayName: Run Tests
            inputs:
              filePath: ./build.ps1
              arguments: -Tasks test
              pwsh: $(usePwsh)

          - task: PublishTestResults@2
            displayName: Publish Test Results
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: NUnit
              testResultsFiles: $(buildFolderName)/$(testResultFolderName)/NUnit*.xml
              testRunTitle: $(platformName)

          - task: PublishPipelineArtifact@1
            displayName: Publish Coverage Artifact
            condition: succeededOrFailed()
            inputs:
              targetPath: $(buildFolderName)/$(testResultFolderName)
              artifactName: CodeCoverage_$(platformName)_$(System.JobAttempt)
              parallel: true

      - job: HQRM
        displayName: HQRM
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              buildType: current
              artifactName: $(buildArtifactName)
              targetPath: $(Build.SourcesDirectory)/$(buildFolderName)

          - task: PowerShell@2
            displayName: Run HQRM Tests
            inputs:
              filePath: ./build.ps1
              arguments: -Tasks hqrmtest
              pwsh: true

          - task: PublishTestResults@2
            displayName: Publish HQRM Results
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: NUnit
              testResultsFiles: $(buildFolderName)/$(testResultFolderName)/NUnitXml_HQRM*.xml
              testRunTitle: HQRM

      - job: Code_Coverage
        displayName: Publish Code Coverage
        dependsOn:
          - Test
        condition: succeededOrFailed()
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              buildType: current
              artifactName: $(buildArtifactName)
              targetPath: $(Build.SourcesDirectory)/$(buildFolderName)

          - ${{ each platform in parameters.PlatformMatrix }}:
              - task: DownloadPipelineArtifact@2
                displayName: Download Coverage ${{ platform.Key }}
                inputs:
                  buildType: current
                  artifactName: CodeCoverage_${{ platform.Value.platformName }}_$(System.JobAttempt)
                  targetPath: $(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)

          - task: PowerShell@2
            displayName: Merge Code Coverage
            inputs:
              filePath: ./build.ps1
              arguments: -Tasks merge
              pwsh: true

          - task: PublishCodeCoverageResults@2
            displayName: Publish Azure Code Coverage
            inputs:
              summaryFileLocation: $(buildFolderName)/$(testResultFolderName)/JaCoCo_coverage.xml
              pathToSources: $(Build.SourcesDirectory)

  - stage: Deploy
    dependsOn: Test
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        ),
        contains(variables['System.TeamFoundationCollectionUri'], 'dsccommunity')
      )
    jobs:
      - job: Deploy_Module
        displayName: Deploy Module
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              buildType: current
              artifactName: $(buildArtifactName)
              targetPath: $(Build.SourcesDirectory)/$(buildFolderName)

          - task: PowerShell@2
            displayName: Publish Release
            inputs:
              filePath: ./build.ps1
              arguments: -Tasks publish
              pwsh: true
            env:
              GitHubToken: $(GitHubToken)
              GalleryApiToken: $(GalleryApiToken)
              ReleaseBranch: $(defaultBranch)
              MainGitBranch: $(defaultBranch)
