---
BuiltModuleSubdirectory: module
CopyPaths:
  - en-US
Encoding: UTF8
VersionedOutputDirectory: true

BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  docs:
    - Create_Wiki_Output_Folder
    - Generate_Markdown_For_Public_Commands
    - Generate_External_Help_File_For_Public_Commands
    - Clean_Markdown_Of_Public_Commands
    - Copy_Source_Wiki_Folder
    - Generate_Wiki_Sidebar
    - Clean_Markdown_Metadata
    - Package_Wiki_Content

  pack:
    - build
    - docs
    - package_psresource_nupkg

  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Convert_Pester_Coverage
    - Pester_if_Code_Coverage_Under_Threshold

  merge:
    - Merge_CodeCoverage_Files

  publish:
    - Publish_Release_To_GitHub
    - publish_module_to_gallery
    - Publish_GitHub_Wiki_Content
    - Create_ChangeLog_GitHub_PR

Pester:
  Configuration:
    Run:
      Path:
        - tests/QA
        - tests/Unit
    Filter:
      ExcludeTag:
        - Changelog
        - FunctionalQuality
        - TestQuality
        - helpQuality
    Output:
      Verbosity: Detailed
      StackTraceVerbosity: Full
      CIFormat: Auto
    CodeCoverage:
      CoveragePercentTarget: 80
      Path:
        - source/Public/*.ps1
      OutputEncoding: ascii
      UseBreakpoints: false
    TestResult:
      OutputFormat: NUnitXML
      OutputEncoding: ascii
  ExcludeFromCodeCoverage:
    - output

CodeCoverage:
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml
  CodeCoverageFilePattern: CodeCov*.xml

DscTest:
  Pester:
    Configuration:
      Filter:
        ExcludeTag:
          - Common Tests - New Error-Level Script Analyzer Rules
          - Common Tests - Validate Localization
          - Common Tests - Validate Example Files To Be Published
          - Common Tests - Validate Example Files
      Output:
        Verbosity: Detailed
        CIFormat: Auto
      TestResult:
        OutputFormat: NUnitXML
        OutputEncoding: ascii
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
  Script:
    ExcludeSourceFile:
      - output
    MainGitBranch: master

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.Test:
    - 'Task.*'
  DscResource.DocGenerator:
    - 'Task.*'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitConfig:
  MainGitBranch: master

GitHubConfig:
  GitHubFilesToAdd:
    - CHANGELOG.md
  ReleaseAssets:
    - output/WikiContent.zip
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false

DscResource.DocGenerator:
  Publish_GitHub_Wiki_Content:
    Debug: false
  Generate_Wiki_Sidebar:
    Debug: false
    AlwaysOverwrite: true
