---
OutputGenerator:
  # cmd:
  #   kind: '&'
  #   spec: |
  #     choco list --help
  cmd0:
    kind: string
    spec: |
      Just some multiline
      output for parsing
  cmd1: |
    Just some multiline
    output for parsing


Sections:
  ParserSection:
    StartWith: abc
    Until: forever
  ParserSectionWithSub:
    kind: ParserSubSection
    spec:
      startwith: stuff
      until: more stuff
      Sections:
        stuff:
          startwith: nothing
  stuff:
    kind: PropertyValueParser
    spec:
      AllowedPropertyName: ['Property1','Property2']
      ExtraProperty: Discard # | AddToKey
      # ExtraPropertyKey: ExtraProperty
      LineNotMatched: AppendToPreviousProperty # | Discard | Verbose | Debug
      # the following lines parsed will be added as key/values of the same objects (instead of nested objects)
      Regexes:
        - Pattern: ^\s*(?<property>[\w-\s]*):\s*(?<value>.*)$
          CaseSensitive: false
          AllowNullValue: true
          NamedGroupAsPropertyName: true
          break: false
        # The Named group regex MUST be property/value
        - (\s\s)*(?<property>[^\s]+)\s(?<value>[^\s]+)
      Transform: hashtable # OrderedDictionary | PSObject

  # ChocoVersion:
  #   Kind: ObjectMatch
  #   Spec:
  #     Regex: ^(?<Name>[^\s]+)\s*v(?<version>[^\s]*)\s*\((?<stuff>[^\)]*)\)
  #     Properties: ['Name','Stuff','Version']
  #     Transform: PSCustomObject

      # startwith: FirstLine
      # until: blank_line
      # DoAfter: stop # next | loop | GOTO:ChocoVersion
